spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://host.docker.internal:9092/~/test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-
      settings:
        web-allow-others: true

  logging:
    level:
      root: info
      com.portfolio.weather: debug
      org.springframework: info
      org.mybatis: debug
      org.mybatis.spring: debug